---

- hosts:  all
  become:  true
  tasks:

  - name:  update repository index
    dnf:
      update_cache:  yes
    when:  ansible_distribution == "CentOS"

  - name:  install httpd and php packages for Centos
    dnf:
      name:  
        - httpd
        - php
      state:  latest
    when:  ansible_distribution == "CentOS"
