---

- hosts:  all
  become:  true
  tasks:

  - name:  update repository index
    dnf:
      update_cache:  yes
    when:  ansible_distribution == "CentOS"

  - name:  install httpd package
    dnf:
      name:  httpd
      state:  latest
    when:  ansible_distribution == "CentOS"
